---
  - name: Extract artifact.tar.gz file to EC2 Instance 
    unarchive:  
      src:  ../../backend/artefacts.tar.gz
      dest: /home/ubuntu/
      owner: ubuntu 
      remote_src: no
  
  - name: Extract artifact.tar.gz file to EC2 Instance 
    unarchive:  
      src:  ../../artefacts.tar.gz
      dest: /home/ubuntu/
      owner: ubuntu 
      remote_src: no

  
  - name: "install dependencies nodejs npm"
    become: yes
    apt:
      name: ["nodejs", "npm"]
      state: present
      update_cache: yes    
          
  
  - name: "Install netstat tool"
    become: yes
    apt:
      name:  ["net-tools"]
      state: latest
      update_cache: yes  

  - name: "update apt packages."
    become: yes
    become_method: sudo
    apt:
      update_cache: yes

 
  - name: "pm2 install global "
    become: yes
    shell: |
          cd /home/ubuntu/
          npm install pm2 -g
          
  - name: "Start App"
    become: yes
    # remote_user: ubuntu 
    become_user: ubuntu  
    # command: 
    shell: | 
        cd /home/ubuntu/dist
        pm2 list 
        pm2 stop default 
        pm2 start main.js -n 'udapeople-backend'
        pm2 status all
        netstat -tulpn
        curl localhost:3030/api/status
        netstat -tulpn
      # pm2 start npm -- start 
      # export NODE_PATH=/home/ubuntu/dist/node_modules
      # command: cd backend && pm2 start nodejs && pm2 start npm -- start --port 3030
    ignore_errors: true    
    # environment:
    #   NOD_ENV: production
    #   ENVIRONMENT: production
    #   NODE_PATH: /home/ubuntu/dist/node_modules
    #   TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    #   TYPEORM_MIGRATIONS_DIR: "./migrations"
    #   TYPEORM_MIGRATIONS: "./migrations/*.js"
    #   TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
    #   TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    #   TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    #   TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    #   TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    #   TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"

