---

  # - name: Extract artifact.tar.gz file to EC2 Instance 
  #   unarchive:  
  #     src:  ../../artefacts.tar.gz
  #     dest: /home/ubuntu/
  #     owner: ubuntu 
  #     remote_src: no

  # - name: "Copy package.json to EC2"
  #   become: yes
  #   copy:
  #     src: ../../backend/package.json
  #     dest: /home/ubuntu/
  #     owner: ubuntu

 
  # - name: "update apt packages."
  #   become: true
  #   become_method: sudo
  #   apt:
  #     update_cache: yes
      
  
  # - name: "install dependencies nodejs npm"
  #   become: yes
  #   apt:
  #     name: ["nodejs", "npm", "pm2"]
  #     state: latest
  #     update_cache: yes        

  
  # - name: "Install netstat tool"
  #   become: yes
  #   apt:
  #     name:  ["net-tools"]
  #     state: latest
  #     update_cache: yes  
            
 
  # - name: "pm2 install global "
  #   become: true
  #   command: npm install pm2 -g

  
  # - name: "pm2 startup "
  #   become: true
  #   shell: |
  #       cd backend
  #       echo 'inside backend folder-1...'
  #       export NODE_PATH=/home/ubuntu/backend/node_modules
  #       echo $NODE_PATH
  #       pm2 startup
  - name: "Start App"
    become: true
    # command: 
    shell: | 
        pm2 start npm -- start -- port 3030
        curl localhost:3030/api/status
    # pm2 stop default
    # pm2 start npm -- start -- port 3030
    # netstat -tulpn
    # curl localhost:3030/api/status
    # npm install pm2 -g 
    # pm2 update
    # cd /home/ubuntu
    # cd backend
    # pm2 list all
    # pm2 stop default 
    # command: cd backend && pm2 start nodejs && pm2 start npm -- start --port 3030
    ignore_errors: true    
    environment:
      NOD_ENV: production
      ENVIRONMENT: production
      NODE_PATH: /home/ubuntu/backend/node_modules
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
      TYPEORM_MIGRATIONS: "./migrations/*.ts"
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity.ts"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"

