---

  - name: Extract artifact.tar.gz file to EC2 Instance 
    unarchive:  
      src:  ../../artefacts.tar.gz
      dest: /home/ubuntu/
      owner: ubuntu 
      remote_src: no

  - name: "Copy package.json to EC2"
    become: yes
    copy:
      src: ../../backend/package.json
      dest: /home/ubuntu/
      owner: ubuntu

 
  - name: "update apt packages."
    become: true
    become_method: sudo
    apt:
      update_cache: yes
      
  

  - name: "install pm2"
    become: yes
    npm:
      name: pm2
      global: yes
      production: yes
      state: present    
  
  - name: "install dependencies nodejs npm"
    become: yes
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes        

  # - name: "Stop pm2 that might already be running"
  #   become: true
  #   command: pm2 stop default
  #   ignore_errors: true    
  #   file:
  #     path: /home/ubuntu/backend/
  #     state: directory
  #   # args:
  #   #   chdir: /home/ubuntu/backend/

  - name: "Start App"
    become: true
    # command: 
    shell: | 
            export NODE_PATH=/home/ubuntu/backend/node_modules
            echo $NODE_PATH
            sudo apt install net-tools
            cd backend
            pm2 npm start 
            netstat -tulpn
    # command: cd backend && pm2 start nodejs && pm2 start npm -- start --port 3030
    ignore_errors: true    
    # args:
    #   chdir: /home/ubuntu/backend/
      # chdir: /home/ubuntu/backend/
    environment:
      # ENVIRONMENT: production
      NOD_ENV: production
      ENVIRONMENT: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
      TYPEORM_MIGRATIONS: "./migrations/*.ts"
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity.ts"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"

